### ISSUE TITLE
HREF not exiting current page.

### ISSUE THREAD

**Issue by jodriscoll** [rewdy/leaveNotice#1]
Plugin Used: leaveNotice (https://github.com/rewdy/leaveNotice/)
Working Example: http://www.massgeneral.org/digestive/services/ostomy-test.aspx

Step 1: Click one of the bottom three links
Step 2: Click the "CONTINUE" button
Issue: You are not brought to the href/url the button is pulling from and attached too. Any idea why this is happening?

**Comment by jodriscoll** [comment]
I found the issue. I had my two buttons sharing the same class "mghBtn" which was always bound to the #close functionality. What I did was attach a new class to the "BACK" button and bound that to the #close functionality and that solved my issue.

**Comment by rewdy** [comment]
@jodriscoll Ooops. I just got around to looking at this now. I'm glad you were able to solve the problem. Hope the plugin is useful for you. Cheers.
